<a href="https://colab.research.google.com/github/GuoyaoShen/DiatomDL/blob/main/load_data_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mount Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Data Loading
* might need stacking data in future

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import datasets, transforms

In [ ]:
path_reflection = '/content/drive/My Drive/BU Class/Research/BioDL_Project/data/test1.txt'
# path_reflection = '/content/drive/My Drive/BU Class/Research/BioDL_Project/data/Diatom_vis_1_reflection.txt'

# data_reflection = np.loadtxt(path_reflection, skiprows=2)
data_reflection = np.loadtxt(path_reflection)

In [ ]:
print(data_reflection.shape)
print(data_reflection)
print(data_reflection[:,0])

(25025, 2)
[[3.75000000e+02 9.40925333e-01]
 [3.75375000e+02 9.40649210e-01]
 [3.75750000e+02 9.40379784e-01]
 ...
 [7.49250000e+02 1.36811020e-01]
 [7.49625000e+02 1.36820749e-01]
 [7.50000000e+02 1.36830704e-01]]
[375.    375.375 375.75  ... 749.25  749.625 750.   ]


In [ ]:
# test
import numpy as np
# a = np.NaN
a = np.array([]).reshape(0,3)
b = np.array([1,2,3])
c = np.array([1,2,7])
d = np.vstack((a,b,c))

print(d)

[[1. 2. 3.]
 [1. 2. 7.]]


In [ ]:
# CORE PART OF READING DATA

import numpy as np



num_combination = 0
with open(path_reflection) as f:
    lines=f.readlines()

    spectra_ref_all = np.array([]).reshape(0,1001,2)  # shape for each spectra: [1001,2]
    spectra_ref = np.array([]).reshape(0,2)
    param_all = np.array([]).reshape(0,11)

    for i, line in enumerate(lines):
        if (i%1004!=0) & (i%1004!=1) & (i%1004!=2): # read spectra data
            line_array = np.fromstring(line, dtype=float, sep=' ')
            # print(i)
            # print(spectra_ref.shape)
            # print(line_array)
            # print(line_array.shape)
            # print('=====')
            spectra_ref = np.vstack((spectra_ref, line_array))

        if i%1004==0:  # every (3+1001) lines, read param title
            # print(num_combination, i, line.strip())
            param = [float(s) for s in re.findall(r"[-+]?\d*\.\d+|\d+", line)]  # extract the float param
            print(num_combination, param)
            print('------------')
            param_all = np.vstack((param_all, param))
            num_combination += 1

        if i%1004==1003:  # every end of the combination, concat
            print(num_combination)
            spectra_ref_all = np.concatenate((spectra_ref_all, spectra_ref[np.newaxis, ...]), axis=0)
            spectra_ref = np.array([]).reshape(0,2)

0 [0.5, 0.04, 0.0, 0.17, 0.0, 0.7794, 0.45, 0.1, 0.03, 0.02, 0.0]
------------
1
1 [0.5, 0.05, 0.0, 0.17, 0.0, 0.7794, 0.45, 0.1, 0.03, 0.02, 0.0]
------------
2
2 [0.5, 0.06, 0.0, 0.17, 0.0, 0.7794, 0.45, 0.1, 0.03, 0.02, 0.0]
------------
3
3 [0.5, 0.07, 0.0, 0.17, 0.0, 0.7794, 0.45, 0.1, 0.03, 0.02, 0.0]
------------
4
4 [0.5, 0.08, 0.0, 0.17, 0.0, 0.7794, 0.45, 0.1, 0.03, 0.02, 0.0]
------------
5
5 [0.5, 0.09, 0.0, 0.17, 0.0, 0.7794, 0.45, 0.1, 0.03, 0.02, 0.0]
------------
6
6 [0.5, 0.1, 0.0, 0.17, 0.0, 0.7794, 0.45, 0.1, 0.03, 0.02, 0.0]
------------
7
7 [0.5, 0.11, 0.0, 0.17, 0.0, 0.7794, 0.45, 0.1, 0.03, 0.02, 0.0]
------------
8
8 [0.5, 0.12, 0.0, 0.17, 0.0, 0.7794, 0.45, 0.1, 0.03, 0.02, 0.0]
------------
9
9 [0.5, 0.13, 0.0, 0.17, 0.0, 0.7794, 0.45, 0.1, 0.03, 0.02, 0.0]
------------
10
10 [0.5, 0.04, 0.0, 0.16, 0.0, 0.7794, 0.45, 0.1, 0.03, 0.02, 0.0]
------------
11
11 [0.5, 0.05, 0.0, 0.16, 0.0, 0.7794, 0.45, 0.1, 0.03, 0.02, 0.0]
------------
12
12 [0.5, 0.06, 0.0, 0.16

In [ ]:
print(spectra_ref_all.shape)
print(param_all.shape)

(25, 1001, 2)
(25, 11)


In [ ]:
import re 

test_string = '#Parameters = {add_spa=0.5; d=0.09; fillet=0; p=0.15; phi=0; px=0.7794; py=0.45; t_ground=0.1; t_pattern=0.03; t_spacer=0.02; theta=0}'
# test_string = "There are 2 apples for 4 persons"

# res = [int(i) for i in test_string.split('=') if i.isdigit()]
# print(res)



# temp = re.findall("\d+\.\d+", test_string)
# res = list(map(float, temp))
# print(temp)

param = [float(s) for s in re.findall(r"[-+]?\d*\.\d+|\d+", test_string)]
print(param)

[0.5, 0.09, 0.0, 0.15, 0.0, 0.7794, 0.45, 0.1, 0.03, 0.02, 0.0]
